added S46 and S48 to build instructions
nasa-jpl/open-source-rover pull request #228
Opened 2020-11-19 19:41 UTC by mattbhenley

2020-11-20 00:32 UTC, JHPHELAN commented
@mattbhenley 
Under Assembling the Base Wheel Mounts, in the parts list, the image for S48 Pattern Adapter shows the threaded plate instead.

2020-11-20 03:05 UTC, mattbhenley commented
@JHPHELAN thanks for catching that! I've updated that image reference for S48

2020-11-30 15:43 UTC, Achllle requested changes
Thanks for your contribution, @mattbhenley! If I'm not mistaken, these should go in the table above it.

2020-11-30 15:43 UTC, Achllle commented on Mechanical/Wheel Assembly/README.md
> +
I believe these should get added to the table that comes before this one since S46 and S48 are used earlier.

2020-12-01 20:16 UTC, mattbhenley reviewed
Yup, definitely in the wrong table. Thanks for catching that and letting me know. Good learn

2020-12-01 20:17 UTC, mattbhenley commented
@Achllle appreciate the patience. I made the change and added S46 and S48 to the correct table. Thanks for letting me do this

2020-12-01 22:22 UTC, Achllle approved these changes
Lgtm, thanks for your contribution!

2020-12-01 22:23 UTC, merged