WIP: Port PCB Assembly doc to markdown
nasa-jpl/open-source-rover pull request #240
Opened 2021-01-17 21:22 UTC by SConaway

Closes #222

Refer to [this project](https://github.com/nasa-jpl/open-source-rover/projects/1) for context.

To-do:
- [] Remove unused images
- [] Remove LaTeX files and PDFs

2021-01-17 21:23 UTC, SConaway commented
Should we include a `.prettierrc` in the root dir? I'm using VSCode with the Prettier extension (a common setup) and here's mine:
```js
module.exports = {
    proseWrap: 'always',
    printWidth: 80,
};
```

2021-01-17 21:33 UTC, SConaway commented
to figure out which images should be kept, I deleted them all, then `git restore`d any mentioned by `pandoc -s "PCB Assembly.md" -o pdf.pdf`

2021-01-28 02:40 UTC, ericjunkins submitted a review, later dismissed
Hi @SConaway just took a look at this, I have a few comments here: 

- [x] Migrate the format to use what we have with this readme that's already done: https://github.com/nasa-jpl/open-source-rover/tree/master/mechanical/wheel_assembly . This will help solve some of the spacing issues with tables etc. 
- [ ] I think we should have the README's in their own folder so they are what appears by default on a page. So if you navigate to electrical/pcb/ it has the PCB build doc there. ([handling here](https://github.com/nasa-jpl/open-source-rover/issues/252))
- [x] We should remove the old latex documents and pdfs to remove confusion once all things are migrated

Thanks for the work on this so far, it looks like a huge amount of the work on this is done and just needs a little more to polish it

2021-01-28 04:10 UTC, SConaway commented
@ericjunkins 

I'll get started on those changes soon, so hopefully they'll be finished in a week or so. 

I was testing in VSCode's Markdown preview, so that's probably why I didn't see the images were way too big. For the formatting changes, is there anything else I need to fix besides image sizing? Thanks!

2021-01-30 01:34 UTC, SConaway commented
Added image size, not sure if there are any other formatting tweaks to make. Personally, I don't like the two-items-per-row in a table as it makes it hard to maintain

2021-01-30 01:36 UTC, SConaway commented
Moved to own folder, and I don't think there are any PDFs/TeX files left for this PR.

2021-02-25 03:11 UTC, dcschooley commented
I'll take a look at this one.

2021-03-10 23:39 UTC, apollokit requested changes
looks really good! All the content is there and looks correct, just needs some formatting updates

2021-03-10 23:39 UTC, apollokit commented on electrical/PCB Assembly/README.md
> +| Soldering Iron         | N/A     |         |                                                                 |
Make double column

2021-03-10 23:39 UTC, apollokit commented on electrical/PCB Assembly/README.md
> +| Soldering Iron        | N/A     |         |                                                                                 |
double column

2021-03-10 23:39 UTC, apollokit commented on electrical/PCB Assembly/README.md
> +    ![Assembly Step 1](./../images/pcb_assembly/assembly/assembly_1.png)
fix pics here and below (also make sure they conform to the new picture locations on master branch)

2021-03-10 23:39 UTC, apollokit commented on electrical/PCB Assembly/README.md
> +| Diode             | E17     | 1       | <img src="/images/components/electronics/E17.png" height="100"> |
Diode is extraneous here

2021-03-10 23:39 UTC, apollokit commented on electrical/PCB Assembly/README.md
> +[Software Install steps](https://github.com/nasa-jpl/open-source-rover/blob/master/Software/Software%20Steps.pdf)
need to update this reference. Should just refer to the setup section in: https://github.com/nasa-jpl/osr-rover-code

2021-03-11 00:02 UTC, apollokit commented
Headsup! I'm taking a crack at this right now, I think that'll minimize work overall

2021-03-11 00:07 UTC, SConaway commented
Alright cool! Just let me know if there's anything to work on and I'll do that

2021-03-11 00:12 UTC, apollokit commented
> Alright cool! Just let me know if there's anything to work on and I'll do that

Roger.

Also, I'll probably need you to approve my updates to the branch, I don't think I can push updates directly to your fork. Might just do a new PR. A PR for your PR. ("yo dawg, I heard you like PRs")

2021-03-11 00:23 UTC, SConaway commented
> Also, I'll probably need you to approve my updates to the branch, I don't think I can push updates directly to your fork. Might just do a new PR. A PR for your PR. ("yo dawg, I heard you like PRs")

You should be able to, but I'm not completely sure. You can always open a PR to this branch on my fork and then I can merge it there then this one can be merged...there has to be a better way to do that. 

I think maintainers can push to PRs (if the button's checked), see the attached screenshot
![CleanShot 2021-03-10 at 16 23 01](https://user-images.githubusercontent.com/20807660/110716891-e756eb00-81bc-11eb-8f3f-8883b224b3f0.png)

2021-03-11 00:24 UTC, apollokit commented
> > Also, I'll probably need you to approve my updates to the branch, I don't think I can push updates directly to your fork. Might just do a new PR. A PR for your PR. ("yo dawg, I heard you like PRs")
> 
> You should be able to, but I'm not completely sure. You can always open a PR to this branch on my fork and then I can merge it there then this one can be merged...there has to be a better way to do that.
> 
> I think maintainers can push to PRs (if the button's checked), see the attached screenshot
> ![CleanShot 2021-03-10 at 16 23 01](https://user-images.githubusercontent.com/20807660/110716891-e756eb00-81bc-11eb-8f3f-8883b224b3f0.png)

Right right, I meant a PR for this branch on your fork. I'm assuming I'll have to do that because your fork's branch is the source of this PR. Shrug, we'll see.

2021-03-11 03:05 UTC, apollokit commented
Oh, nice, it let me push straight up.

@SConaway can you give it a look-see , make sure I didn't screw anything up, and then merge?

2021-03-11 03:08 UTC, apollokit approved these changes

2021-03-11 03:27 UTC, SConaway commented
@apollokit looks like you were able to add commits directly to this PR. 😃

2021-03-25 01:43 UTC, merged

2021-03-25 01:47 UTC, apollokit commented
Handling @ericjunkins 's wish to reorg electrical readmes in this issue: https://github.com/nasa-jpl/open-source-rover/issues/252