Differential pivot readme
nasa-jpl/open-source-rover pull request #246
Opened 2021-01-28 01:35 UTC by ericjunkins

Redo the differential pivot readme instructions

2021-01-28 02:34 UTC, Achllle requested changes
Left comments

2021-01-28 02:34 UTC, Achllle commented on mechanical/differential_pivot/README.md
Empty table? I removed this table as a whole for the corner steering

2021-01-28 02:34 UTC, Achllle commented on mechanical/differential_pivot/README.md
>  ### Optional
consider removing, it just sits there randomly

2021-01-28 02:34 UTC, Achllle commented on mechanical/differential_pivot/README.md
> +1. Aluminum Rods: Cutting
In the other readmes (and the template) we use headings instead of numbered lists.

So `### 3.1 Aluminum Rods: Cutting`

2021-01-28 02:34 UTC, Achllle commented on mechanical/differential_pivot/README.md
> +  | Allen Key Set | D2 | 1 | <img src="/images/components/tools/D2.png" width="25%"> |
consider splitting up into two columns, that way it's more compact

2021-01-28 02:34 UTC, Achllle commented on mechanical/differential_pivot/README.md
> +  | RC Turnbluckle | S32 | 2 |<img src="/images/components/structural/S32.jpg" width="25%">|
```suggestion
  | RC Turnbluckle | S32 | 2 |<img src="/images/components/structural/S32.png" width="25%">| 
```

2021-01-28 02:34 UTC, Achllle commented on mechanical/differential_pivot/README.md
> +  | 0.5" Bottom Bore Clamp | S20 | 2 | <img src="/images/components/structural/S20pngjpg" width="25%">|
```suggestion
  | 0.5" Bottom Bore Clamp | S20 | 2 | <img src="/images/components/structural/S20.png" width="25%">| 
```

2021-03-16 23:22 UTC, ericjunkins commented
@Achllle ready for re-review, fixed the things you had commented on for fixing

2021-03-16 23:55 UTC, Achllle reviewed
In some sections like 4.1.1 the title appears on the next line

2021-03-17 00:01 UTC, ericjunkins commented
yep looks like that was true in section 4.1.x, fixed them

2021-03-17 03:50 UTC, Achllle approved these changes
great work!

2021-03-17 04:29 UTC, merged